version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: aupo_postgres
    hostname: aupo_postgres
    expose:
      - 5432
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=aupo
  backend:
    image: openjdk:17
    container_name: aupo_backend
    expose:
      - 8080
    ports:
      - 8080:8080
    volumes:
      - ./target/aupo-0.1.jar:/opt/app.jar
    command: java -jar -Ddb.url=jdbc:postgresql://aupo_postgres:5432/aupo /opt/app.jar