version: '3.9'
services:
  postgres:
    image: postgres:14-alpine
    container_name: aupo_postgres
    expose:
      - 5432
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USERNAME=postgres
      - POSTGRES_DB=aupo